export const actionType = {
  CREATE: 'CREATE',
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  GET_ALL: 'GET_ALL',
  GET_ALL_CLASS: 'GET_ALL_CLASS',
  GET_ALL_TRAINER: 'GET_ALL_TRAINER',
  GET_ALL_TRAINEE: 'GET_ALL_TRAINEE',
  GET_ALL_SUBJECT: 'GET_ALL_SUBJECT',
  GET_ALL_MARK: 'GET_ALL_MARK',
  VALUE_CHANGE: 'VALUE_CHANGE',
  NULL_ALL: 'NULL_ALL',
};
