export const actionType = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  EMAIL_CHANGE: 'EMAIL_CHANGE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  ERROR: 'ERROR',
  SIGN_OUT: 'SIGN_OUT',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
  LOCKED: 'LOCKED',
  UN_LOCKED: 'UN_LOCKED',
};
